### ISSUE TITLE
Dear author, i am so curious about the following picture. It's so gorgeous. How was it derived from?(Which tool can be used to draw it?)

### ISSUE THREAD

**Issue by 2226123114** [wdvorkin/LDR_for_gas_network_control#1]
![image](https://user-images.githubusercontent.com/96046064/156327829-05471d8f-f352-4683-a56f-0ed549bd6dca.png)

**Comment by wdvorkin** [comment]
Hi, and thanks for your interest! Here, a `Tikz` package in LaTeX is used to draw the gas network, Julia Language is used to run Kernel Density Estimation on a grid (to smooth the variance solution around the centers of each edge), and function `geom_contour_filled` from 'ggplot2' in R is used to visualize the density.

**Comment by 2226123114** [comment]
Thanks a lot for your answer! I am trying hard to learn it.
