### ISSUE TITLE
Hi, is there a pure Matlab version of your code? Unfortunately, I failed to use Mosek for Julia due to some limitations, and I am not familiar with Julia lang.

### ISSUE THREAD

**Issue by 2226123114** [wdvorkin/LDR_for_gas_network_control#2]

**Comment by wdvorkin** [comment]
Sorry, the whole project is written in Julia language. However, it is very straightforward to run the code: download Julia language from [here](https://julialang.org/downloads/), get your Mosek license [here](https://www.mosek.com/products/academic-licenses/) (free for academic use), and simply follow instructions in [README.md](https://github.com/wdvorkin/LDR_for_gas_network_control/issues/2#readme)[](https://github.com/wdvorkin/LDR_for_gas_network_control/edit/main/README.md)[](https://github.com/wdvorkin/LDR_for_gas_network_control/issues/2#multi-stage-linear-decision-rules-for-stochastic-control-of-natural-gas-networks-with-linepack). Good luck!
